### ISSUE TITLE
 class org.gradle.initialization.DefaultSettings_Decorated cannot be cast to class org.gradle.api.Project

### ISSUE THREAD

**Issue by drernie** [Im-Fran/SonatypeCentralUpload#5]
I'm sorry if I'm doing something stupid, this is my first time using a Gradle plugin.
I inherited a project that used the legacy `oss.sonatype.org `system (for which we no longer have credentials), and wanted to use your plugin with our new Central Portal credentials.

I think I followed your instructions, but whenever I run `./gradlew` I get:

```
An exception occurred applying plugin request [id: 'cl.franciscosolis.sonatype-central-upload', version: '1.0.3']
> Failed to apply plugin 'cl.franciscosolis.sonatype-central-upload'.
   > class org.gradle.initialization.DefaultSettings_Decorated cannot be cast to class org.gradle.api.Project (org.gradle.initialization.DefaultSettings_Decorated and org.gradle.api.Project are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @3d012ddd)
```

Any suggestions? The actual code is here:
https://github.com/quiltdata/quiltcore-java/pull/11

**Comment by Im-Fran** [comment]
Hi @drernie!

In order to import the plugin you need to add it inside this plugins tag: https://github.com/quiltdata/quiltcore-java/blob/fix-publishing/lib/build.gradle#L9-L14

For what I saw in your project you've included the plugin in the settings.gradle file, but it should go in the build.gradle file actually

**Comment by drernie** [comment]
That did it, thank you!
